### ISSUE TITLE
Open url form terminal makes finicky crash

### ISSUE THREAD

**Issue by tcarlsen** [johnste/finicky#24] opened 2015-08-14 07:04 UTC
I was using the `brew home` command to get the homepage of a library, but nothing happened. Then I notice that finicky was gone in the menubar so I reopened finicky and tried again.  

Nothing, but this time I saw finicky crash!

Making chrome my default browser again and its working like it should.

I also tried writing `open http://google.com` in the terminal and that crashes finicky aswell

**Comment by johnste** [comment] 2015-08-14 11:59
Which version are you running? This bug is fixed in v0.4.

**Comment by johnste** [comment] 2015-08-14 13:14
Duplicate of #12

**Closed by johnste** 2015-08-14 13:14 UTC
Labels: duplicate
