### ISSUE TITLE
Finicky appears in the dock and in "recent applications"

### ISSUE THREAD

**Issue by andersennl** [johnste/finicky#78] opened 2019-10-08 11:49 UTC
Hi, this request is similar to https://github.com/johnste/finicky/issues/41.

In my case though I'd like to leave the menu bar item displayed and instead rather have a config option to hide the dock item. Since the menu bar item is visible by default and allows access to the app, the dock item is redundant. Would it be possible to implement this? Thank you.

**Comment by tbrek** [comment] 2019-10-08 12:20
Where do you see dock icon?

**Comment by andersennl** [comment] 2019-10-08 12:34
![Bildschirmfoto 2019-10-08 um 14 33 26](https://user-images.githubusercontent.com/2667916/66395855-b88d8180-e9d8-11e9-9939-f32542882471.jpg)

I installed the app today after updating to macOS Catalina. Maybe this is the reason?

**Comment by johnste** [comment] 2019-10-08 12:42
Yes hm Catalina is probably the cause

**Comment by andersennl** [comment] 2019-10-08 14:31
In fact, the dock icon is not always displayed. When I quit Finicky and then click on a link, the dock icon doesn't reappear immediately either. However, I haven't found out what the icon is displayed by yet.

**Comment by notDavid** [comment] 2019-10-10 12:03
I'm also seeing the same issue. When i open Finicky from `/Applications/Finicky.app` i do not see the icon in the dock.

If i run `open https://github.com/` in Terminal it also does not show up in the dock.

Then, when i click the same test url in Tweetbot, i do see Finicky in the dock... 🤷🏼‍♂️

**Comment by jondkinney** [comment] 2019-10-11 17:00
Inability to hide from the dock on Catalina here, too. I did an in place upgrade to Catalina FWIW.

**Comment by johnste** [comment] 2019-10-11 19:43
This is where finicky attempts to hide itself from the dock:
https://github.com/johnste/finicky/blob/master/Finicky/Finicky/AppDelegate.swift#L154 (called from https://github.com/johnste/finicky/blob/master/Finicky/Finicky/AppDelegate.swift#L36)

There is no conditional logic that would allow finicky to not hide itself, and I can't find any updated documentation on these flags, so I'm not sure what I could attempt to fix here..

**Comment by smithjw** [comment] 2019-10-12 21:16
Can confirm that Finicky also displays in the Dock for me and always has as I've been running Catalina since beta 2 😅

**Comment by mijkal** [comment] 2019-10-13 19:13
^ Seeing the same after update to Catalina.

**Comment by andersennl** [comment] 2019-10-14 07:13
Could it be a bug in Catalina, which makes the API unreliable?

**Comment by daleeidd** [comment] 2019-10-17 09:16
Amphetamine has a similar issue. Even though it is checked as hidden on startup, it appears in the dock. But if I close the app and open it again, it is hidden. It wasn't an issue before Catalina.

**Comment by johnste** [comment] 2019-10-23 20:39
I'm still waiting to upgrade to Catalina. However, I just released a new version where I attempt to fix the issue by attempting to hide the icon in a couple of different scenarios. Please try it and let me know if it helps. https://github.com/johnste/finicky/releases/tag/v2.2.2

**Comment by smithjw** [comment] 2019-10-23 23:55
@johnste Can confirm that the icon is no longer showing in my dock 🙌🏽

**Comment by andersennl** [comment] 2019-10-24 07:06
It seems to work for me as well (it takes some time for the icon to appear but it hasn't appeared yet). Thanks a lot @johnste !

**Comment by johnste** [comment] 2019-10-25 07:28
Glad to hear. Thanks for creating the issue.

**Comment by notDavid** [comment] 2019-10-26 13:35
@johnste  fyi, not sure if this is related, but i'm seeing the issue that clicking on an url in Tweetbot does not bring Safari to the front. I then have to manually switch to the other virtual desktop where Safari is (the link has openen in Safari.)

**Comment by andersennl** [comment] 2019-10-26 13:43
I’m experiencing the same behavior but I’m not sure if the app is causing it as out of Chrome, Firefox and Safari only Safari seems to have this issue.

**Comment by notDavid** [comment] 2019-10-26 14:09
@andersennl Good to know :)

Setting Safari as the default browser (disabling Finicky) and then executing `open https://github.com/` in Terminal switches to Safari & another virtual desktop correctly.

**Comment by johnste** [comment] 2019-10-26 15:03
This seems like a separate issue. Would you mind adding a new issue for it,
and including your current macos version + finicky version?

Thanks

**Comment by notDavid** [comment] 2019-10-26 16:18
Sure: https://github.com/johnste/finicky/issues/82

**Comment by notDavid** [comment] 2019-12-03 10:56
@johnste fyi this issue seems to be back, i'm seeing Finicky in the "recent applications" section in the Dock... Finicky doesn't stay "opened" (=there is no dot underneath the icon) but it is listed there when i'm clicking urls in Tweetbot.

v2.2.3 (169)

<img width="391" alt="Screenshot 2019-12-03 at 11 51 52" src="https://user-images.githubusercontent.com/1530401/70045080-640f1880-15bb-11ea-8298-5dad93b81645.png">

**Comment by lucianoshl** [comment] 2020-06-20 15:07
+1

**Comment by johnste** [comment] 2020-06-21 08:15
I haven't been able to reproduce this issue, not sure how common it is. Until I can do that I'm not sure what to do unfortunately.

**Comment by alejandroivan** [comment] 2020-09-03 15:27
Yes, it appears on "recent applications" everytime I click on a link. Came here finding a solution actually. If the service is running as a service, I don't get why this icon appears.

**Comment by johnste** [comment] 2020-09-03 15:42
Yes, I suppose it's possible to run the application as a service. Any help or advice in going about turning Finicky into a service is welcome.

**Comment by johnste** [comment] 2020-09-04 17:40
I still can't reliably reproduce this issue locally, so if anyone could assist me in testing this release out I would appreciate it a ton. This version is marked as a pre-release until we can confirm it seems to fix the issue.

https://github.com/johnste/finicky/releases/tag/v3.1.1

**Comment by notDavid** [comment] 2020-09-04 19:35
@johnste I've just installed 3.1.1 and i normally see the finicky doc icon quite often, so i'll report back when i see it appearing again...

**Comment by notDavid** [comment] 2020-09-07 08:17
@johnste Have not seen the icon in the Dock yet since 3 days in version v3.1.1 (246), so the fix seems to be working... 👍

**Comment by alejandroivan** [comment] 2020-09-07 14:36
It's working for me now. No more icon in "recent applications" (tried using two different links that open up different browsers and no issues so far).

**Comment by johnste** [comment] 2020-09-10 09:13
Closing this and the other related issue #123  🙌 
Thanks all for verifying!

**Closed by johnste** 2020-09-10 09:13 UTC
Labels: bug, help wanted
