### ISSUE TITLE
Links from Slack don't open in background in Safari

### ISSUE THREAD

**Issue by vincer** [johnste/finicky#107] opened 2020-04-20 21:55 UTC
When Safari is the default browser, the normal behavior in Slack when I click a link while holding down Command is for the link to open in Safari in the background.

With Finicky as the default browser, Safari comes to the foreground.

My config:

```
module.exports = {
    defaultBrowser: "Safari",
    handlers: [
        {
            match: /zoom.us\/j\//,
            browser: "us.zoom.xos"
        },
    ]
};
```

I'm not sure if this only an issue from Slack or other apps as well.

I searched for other issues, but #71 seems Chrome-only and other ones are old and closed though  they make it seem like this *should* be working.

**Comment by johnste** [comment] 2020-04-21 06:46
Not sure how the normal procedure works when Safari is the default browser. There is a way to create the same behavior in finicky though.

Using [keyboard modifiers](https://github.com/johnste/finicky/#keyboard-modifiers) should work

```js
module.exports = {
  defaultBrowser: "Safari",
  handlers: [
    {
      // Open links in Safari when the option key is pressed
      // Valid keys are: shift, option, command, control, capsLock, and function.
      // Please note that control usually opens a tooltip menu instead of visiting a link
      match: ({ keys }) => keys.command,
      browser: "Safari",
      openInBackground: true
    }
  ]
};
```

**Comment by vincer** [comment] 2020-04-21 16:35
Yep, that works great! 

(Though `openInBackground` has to be inside the `browser` block, but figured that out from the docs.)

Also, I checked with Chrome as my default browser, and apparently links will not open in the background with command pressed there either. Not sure what's so special about the Slack/Safari combo...

I'm very happy with this workaround, but I don't know if you'd still consider this a bug worth fixing so I'll let you decide whether to close this or not.

Thanks for the quick answer and this cool app!

**Comment by johnste** [comment] 2020-04-27 19:14
I looked a bit at this, and I can only reproduce this behavior with Slack and Safari. When opening links in other apps in Safari pressing cmd has no effect. I'll close this for now since I don't see any reason to reproduce this. 

Thanks fo the feedback!

**Closed by johnste** 2020-04-27 19:14 UTC
Labels: question
