### ISSUE TITLE
Bug: `openInBackground: true` does not work in Chromium-based Browsers

### ISSUE THREAD

**Issue by chrisgrieser** [johnste/finicky#252] opened 2022-03-16 10:05 UTC
First, thank you so much for this fantastic utility!

**Describe the bug**
Using `openInBackground: true` does not work in Brave and Chromium, the link still opens in the foreground. With Safari as Browser, however, it does work as intended. I assume the issue is associated with Chromium-based browsers?

**Your configuration**

```js
// copypasted from the example configuration.
{
      match: ["http://zombo.com"],
      browser: {
        name: "Brave Browser", // <- only this changed
        // Force opening the link in the background
        openInBackground: true
      }
},
```

**Comment by tsuliwaensis** [comment] 2022-03-17 01:26
This is due to a long-standing bug with Chromium ([Issue 854609](https://bugs.chromium.org/p/chromium/issues/detail?id=854609)). [Comment 22](https://bugs.chromium.org/p/chromium/issues/detail?id=854609#c22) and [Comment 26](https://bugs.chromium.org/p/chromium/issues/detail?id=854609#c26) explains why this is a difficult bug to fix.

**Comment by johnste** [comment] 2022-04-10 08:21
The issues was mentioned here https://github.com/johnste/finicky/issues/71 and I haven't found a way to work around it, sadly. Closing this as duplicate of #71

**Closed by johnste** 2022-04-10 08:21 UTC
Labels: bug
