### ISSUE TITLE
Add a share extension

### ISSUE THREAD

**Issue by j-f1** [johnste/finicky#180] opened 2021-03-09 23:29 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, I want to use Finicky to open a link from my browser. There isn’t a good way to do this.

**Describe the solution you'd like**
Add a “Finicky” or “Open in Finicky” share extension so I can right-click a link and choose Share → Finicky to open the link via Finicky.

**Describe alternatives you've considered**
I’m not sure there are any — I doubt there’s a way to detect when links are opened in e.g. Safari.

**Additional context**
N/A

**Comment by johnste** [comment] 2021-03-10 06:30
I agree, it would be a good addition. Just requires someone to do all that work. :)

Closing this since it's a duplicate of https://github.com/johnste/finicky/issues/161

**Closed by johnste** 2021-03-10 06:30 UTC
Labels: feature request
