### ISSUE TITLE
Finicky may not have authorization to properly resolve short URLs

### ISSUE THREAD

**Issue by johnjensenish** [johnste/finicky#84] opened 2019-11-08 19:12 UTC
Hello!

We pass around short URLs in our development workflow. The right browser is opened, but it goes to the wrong URL, the site's homepage rather than our development service (GraphiQL specifically). This is because the resolved URL is redirected to an unauthenticated homepage.

I would expect that the unresolved URL is passed to the browser, so that redirects that depend on authorization can succeed.

Repro:

1. Create a bit.ly or other short URL to an address that requires authorization of some sort. For some services, when not authorized, there will be a redirect to another URL, like a home page.
2. Observe that Finicky opens the resolved, redirected URL in your browser of choice. This redirected URL may be the homepage rather than the contents 

Expected:

2. Finicky uses the resolved URL to decide which browser to open and  passes the short URL to the browser for the browser to resolve, because the browser may have authentication which changes the resolved URLs.

**Comment by johnste** [comment] 2019-11-08 19:14
Interesting! I'll have a look.

Thanks for the bug report.

**Comment by johnste** [comment] 2019-11-18 20:52
Trying to understand this more – finicky should only try to resolve the first short url (bit.ly) to the intended final destination, and shouldn't try to do anything else unless that destination is also a short url provider destination.

Since finicky can only resolve short urls over https I haven't set up an API to test this properly, but I did create a short url that I can confirm is working. It doesn't do redirection on failure though. Does the authentication page send back the site homepage in a `Location` header? If that's the case I can see how this could happen.

Test url I generated: https://bit.ly/2QthoPt

![image](https://user-images.githubusercontent.com/886051/69092753-5d29c700-0a4d-11ea-9bd0-1b58d05f842d.png)

**Comment by johnjensenish** [comment] 2019-11-18 21:14
Unfortunately I cannot post a concrete, failing example in public, because it is sensitive. I can share over email if you reach out: john dot jensen at subREMOVEstantial dot com without the word "REMOVE" ;)

What I have is a bit.ly URL which resolves to a development website. I followed along in Chrome and saw that bit.ly responds with a HTTP 301 with `Location: <development URL>`. Next, the development URL is requested and because the client is not authorized, we receive a HTTP 302 response with `Location: <public homepage URL>`.

In Finicky console, what I see is: `Would open url: <public homepage URL>`. So what I think is happening is that it follows the redirects all the way through to the public URL. That's why my suggestion is to match based on the resolved URL but to the original, bit.ly URL to the browser.

**Comment by johnste** [comment] 2019-11-18 21:33
I sent you an e-mail. I think I understand what happens now, and if I could test it with your url it should be a pretty fast fix.

**Comment by johnste** [comment] 2019-11-25 23:00
Not a fast fix, but I'm making progress.

**Comment by johnste** [comment] 2019-12-16 09:37
Sorry for this not done yet, been having a hard time getting work done on finicky the last couple of weeks.

**Comment by johnste** [comment] 2020-04-26 16:27
Hi @johnjensenish is this still an issue for you? I think I will make more time to work on finicky for a while.

**Comment by johnjensenish** [comment] 2020-04-28 18:30
Hey @johnste, while I think the issue still exists, I'm not really encountering it in my workflow anymore. (I don't share links of this type on Slack to avoid the issue...)

**Comment by johnste** [comment] 2020-11-22 17:59
Yeah this is a weird one. Sorry for the delay. 

I've spent hours the last couple of days trying to figure this issue out. Every other url I try with works just fine, for example

- https://t.co/wF1NMsx6Fy resolves to the correct https://blog.ahrefs.com/ NOT the redirected destination https://ahrefs.com/blog/
- https://t.co/QPp0uLLxkQ?amp=1 resolves to intended destination https://github.com/johnste/finicky jumping through another redirect

But the example you gave me doesn't work. It follows the redirect.

I found one issue related to the issue – `URL` can't really parse the string provided from the location header. It needs to be able to parse it to detect a "short url provider" like bit.ly or similar. I grabbed a regular expression from somewhere to grab the important parts of the string to be able to parse it if it fails the first time, but it didn't really improve much – it stops directly and doesn't redirect at all (which is better I guess, but not a real fix)

Will look at this some more.

**Comment by johnste** [comment] 2020-11-22 20:21
Ok, so the issue seems to be that url mostly doesn't really like special characters in the url. It also fails at parsing a url like this http://example.com/graphql?test=test#q=test%

**Comment by johnste** [comment] 2020-11-23 19:16
Since the url you provided contains both percent-encoded characters (%0A) as well as characters not allowed in fragments (space, {, }) that need to be encoded to parse correctly, it'll be a challenge to do it well for all urls without double-encoding values.

Current re-evaluating the need to parse urls. Maybe finicky doesn't need to parse urls at all outside of short url provider detection.

**Comment by johnste** [comment] 2021-01-28 17:48
Added a fix to escape urls before parsing them. Released in [3.2.0](https://github.com/johnste/finicky/releases/tag/v3.2.0)

**Closed by johnste** 2021-01-28 17:48 UTC
Labels: bug
